input ClienteFilterInput {
    busca: String
    page: Int!
    size: Int!
}

input ClienteInput {
    id: ID
    nome: String!
    endereco: String!
    telefone: String!
    instagram: String!
}

input PetFilterInput {
    busca: String
    clienteId: Int
    page: Int!
    size: Int!
}

input PetInput {
    id: ID
    nome: String!
    especie: String!
    racaId: ID!
    sexo: String!
    porte: String!
    clienteId: ID!
    observacao: String
    dataNascimento: Date!
}

input ServicoFilterInput {
    busca: String
    page: Int!
    size: Int!
}

input ServicoInput {
    id: ID
    nome: String!
    descricao: String
    precoPequeno: BigDecimal!
    precoMedio: BigDecimal!
    precoGrande: BigDecimal!
}