spring:
  application:
    name: petshop-api

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: ${PORT:8080}

jwt:
  public:
    key: classpath:app.pub
  private:
    key: ${JWT_PRIVATE_KEY}