name: build, test and lint

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  check:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: install and prepare
        run: pnpm install --frozen-lockfile

      - name: run test suites
        run: pnpm test:cov

      - name: lint
        run: pnpm lint

      - name: build
        run: pnpm build
        env:
          ENV_MODE: production